import Link from "next/link";
import { getConfiguredPrivacyServices, interpolateLegalText, textFor, type PrivacyConfig, type PrivacyLang } from "@/lib/privacy/types";

export function LegalPolicyPage({ config, lang, type }: { config: PrivacyConfig; lang: PrivacyLang; type: "privacy" | "cookie" }) {
  const legal = config.legal;
  const isPrivacy = type === "privacy";
  const title = textFor(isPrivacy ? config.privacyPolicy.title : config.cookiePolicy.title, lang);
  const intro = textFor(isPrivacy ? config.privacyPolicy.intro : config.cookiePolicy.intro, lang);
  const services = getConfiguredPrivacyServices(config);
  return (
    <main className="min-h-screen bg-warm-black px-4 py-8 text-ivory sm:px-8 sm:py-16">
      <article className="relative mx-auto max-w-4xl overflow-hidden border border-gold/25 bg-[#171411] px-5 py-9 shadow-[0_34px_120px_rgba(0,0,0,.35)] sm:px-12 sm:py-14">
        <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-gold to-transparent" />
        <nav className="flex flex-wrap items-center justify-between gap-4"><Link href="/" className="font-sans text-[10px] font-bold uppercase tracking-[.2em] text-gold-light">R.G.R. Handmade</Link><div className="flex gap-2">{(["it", "en"] as PrivacyLang[]).map((item) => <Link key={item} href={`/${type === "privacy" ? "privacy-policy" : "cookie-policy"}?lang=${item}`} className={`rounded-full border px-3 py-1 font-sans text-[10px] font-bold ${item === lang ? "border-gold bg-gold text-warm-black" : "border-white/20 text-ivory/60"}`}>{item.toUpperCase()}</Link>)}</div></nav>
        <p className="mt-12 font-sans text-[10px] font-bold uppercase tracking-[.22em] text-gold">Compliance · revisione consenso v{config.version}</p>
        <h1 className="mt-3 max-w-[13ch] font-serif text-[clamp(42px,8vw,76px)] font-light leading-[.92]">{title}</h1>
        <p className="mt-7 max-w-2xl font-sans text-[15px] leading-7 text-ivory/68">{intro}</p>
        {!isPrivacy && <section className="mt-8 border-l border-gold px-5 py-1 font-sans text-[13px] leading-6 text-ivory/62"><strong className="block text-ivory">{legal.legalName}</strong><span>{legal.address}, {legal.postalCode} {legal.city} ({legal.province}) · C.F./P. IVA {legal.vatNumber} · REA {legal.rea}</span><br /><span>PEC {legal.pec} · {legal.privacyEmail}</span></section>}
        {isPrivacy ? <div className="mt-12 grid gap-9">{config.privacyPolicy.sections.filter((section) => section.enabled).sort((a, b) => a.sortOrder - b.sortOrder).map((section, index) => <section key={section.id} className="grid gap-3 border-t border-white/10 pt-7 sm:grid-cols-[48px_1fr]"><span className="font-serif text-2xl text-gold/65">{String(index + 1).padStart(2, "0")}</span><div><h2 className="font-serif text-3xl text-ivory">{textFor(section.title, lang)}</h2><p className="mt-3 whitespace-pre-line font-sans text-[14px] leading-7 text-ivory/66">{interpolateLegalText(textFor(section.body, lang), legal)}</p></div></section>)}</div> : <div className="mt-12 grid gap-5">{config.categories.filter((category) => category.enabled).sort((a, b) => a.sortOrder - b.sortOrder).map((category) => { const categoryServices = services.filter((service) => service.category === category.id).sort((a, b) => a.sortOrder - b.sortOrder); return <section key={category.id} className="border border-white/10 bg-white/[.025] p-5 sm:p-7"><h2 className="font-serif text-3xl">{textFor(category.label, lang)}</h2><p className="mt-2 font-sans text-[13px] leading-6 text-ivory/60">{textFor(category.description, lang)}</p><div className="mt-5 grid gap-3">{categoryServices.length ? categoryServices.map((service) => <div key={service.id} className="border-t border-white/10 pt-4 font-sans text-[12px] leading-5"><strong className="text-ivory">{service.name}</strong><span className="text-ivory/50"> · {service.provider} · {textFor(service.duration, lang)}</span><p className="text-ivory/62">{textFor(service.purpose, lang)}</p></div>) : <p className="font-sans text-[12px] text-ivory/45">{lang === "it" ? "Nessun servizio attivo." : "No active services."}</p>}</div></section>; })}</div>}
        <footer className="mt-12 flex flex-wrap gap-3 border-t border-gold/30 pt-7"><a href={`mailto:${legal.privacyEmail}`} className="rounded-full border border-gold bg-gold px-5 py-3 font-sans text-[10px] font-bold uppercase tracking-[.14em] text-warm-black">{legal.privacyEmail}</a><Link href={isPrivacy ? `/cookie-policy?lang=${lang}` : `/privacy-policy?lang=${lang}`} className="rounded-full border border-ivory/30 px-5 py-3 font-sans text-[10px] font-bold uppercase tracking-[.14em]">{isPrivacy ? "Cookie policy" : "Privacy policy"}</Link>{!isPrivacy && <Link href="/#cookie-settings" className="rounded-full border border-ivory/30 px-5 py-3 font-sans text-[10px] font-bold uppercase tracking-[.14em]">{lang === "it" ? "Gestisci cookie" : "Manage cookies"}</Link>}</footer>
      </article>
    </main>
  );
}
