export const en = {
  nav: {
    home: "Home",
    about: "About",
    collections: "Collections",
    atelier: "Atelier",
    news: "Press",
    contact: "Contact",
  },
  cta: {
    contact: "Contact",
    primary: "Discover RGR",
    secondary: "View collections",
    all: "All collections",
    learn: "Read more",
    info: "Request information",
  },
  header: { since: "Goldsmith atelier · since 1989" },
  hero: {
    eyebrow: "Goldsmith atelier · Arezzo",
    titlePre: "Handcrafted jewellery",
    titleEm: "born in Arezzo",
    lede: "Handcrafted jewellery since 1989: sisters Gallastroni Rossella and Rosaria shape precious metals through traditional techniques and advanced craft. A workshop where matter meets emotion.",
    metaLeft: "Goldsmith workshop · Made in Italy",
    metaRight: "Via Pietro Calamandrei · Arezzo",
  },
  about: {
    eyebrow: "The house",
    titlePre: "A story of hands,",
    titleEm: "metal and light.",
    quote:
      "Materialising emotions into jewels, through a refined creative sense.",
    paragraphs: [
      "RGR was born in Arezzo in 1989 from the synergy of sisters Gallastroni Rossella and Rosaria — a hand-crafting workshop specialised in precious metal manufacturing.",
      "From the very first years the workshop stood out for original creative paths and for studying its signature “wire-wound on template” construction technique.",
      "Over the years the company has specialised in creating jewellery with the most advanced processing technologies — enhancing the care and the beauty of a handmade product.",
      "Today RGR creations are characterised by the highest quality and stand as a true example of how powerful taste, research and creativity make the Made in Italy mark in the world.",
    ],
  },
  pillars: [
    {
      num: "01",
      label: "Since 1989",
      desc: "Thirty-six years of goldsmith work.",
    },
    {
      num: "02",
      label: "Handmade",
      desc: "Each piece born from our craftsmen's hands.",
    },
    {
      num: "03",
      label: "Made in Italy",
      desc: "Tradition and matter, entirely Italian.",
    },
    {
      num: "04",
      label: "Arezzo",
      desc: "Rooted in the Aretine goldsmith district.",
    },
  ],
  manifesto: {
    eyebrow: "RGR manifesto",
    ariaLabel: "Animated RGR manifesto",
    lines: [
      "WE SHAPE LIGHT",
      "WE WORK THE WIRE",
      "WE CRAFT BY HAND",
      "BORN IN AREZZO",
      "MADE IN ITALY BY RGR",
    ],
  },
  catalogue: {
    eyebrow: "Collections",
    titlePre: "Unique lines,",
    titleEm: "wire wound on template.",
    lede: "Sixteen capsule collections crafted to celebrate the wire technique, the metal weave and the light of the stones.",
    tabs: ["All", "Rings", "Bracelets", "Necklaces", "Earrings"],
  },
  atelier: {
    eyebrow: "The workshop",
    titlePre: "Expert hands,",
    titleEm: "evolved technology.",
    paragraphs: [
      "In our Aretine atelier, goldsmith tradition lives alongside the latest manufacturing tools. Every jewel goes through dozens of precise gestures before leaving the bench.",
      "Care for detail is not a finish — it's the way we think of the piece from the very start.",
    ],
    tags: [
      "Craft",
      "Precision",
      "Goldsmith tradition",
      "Technology",
      "Arezzo",
      "Wire wound",
    ],
  },
  news: {
    eyebrow: "Adv Press · Fairs",
    titlePre: "Between international fairs",
    titleEm: "and printed pages.",
    lede: "RGR's presence at trade events and the magazine covers dedicated to our work.",
    filterAll: "All",
    filterFairs: "Fairs",
    filterPress: "Press",
    loadMore: "Load more",
  },
  footer: {
    claim: "Handcrafted jewellery since 1989. RGR turns emotions into jewellery.",
    colVisit: "Atelier",
    addrTitle: "Via Pietro Calamandrei, 253 A/11",
    addrLines: [
      "52100 Arezzo · Italy",
    ],
    form: {
      eyebrow: "Contact",
      title: "Write to us.",
      lede: "For enquiries or studio appointments.",
      detailsTitle: "Studio",
      details: [
        "RGR collections and bespoke jewellery.",
        "Arezzo, by appointment.",
        "Reply within 1-2 business days.",
      ],
      formTitle: "Leave your details.",
      name: "Full name",
      company: "Company / reference",
      email: "Email",
      phone: "Phone",
      message: "Message",
      messagePlaceholder: "Your message",
      privacy: "I consent to the processing of my data to be contacted.",
      submit: "Send",
      note: "We will reply from the studio.",
    },
    colExplore: "Explore",
    explore: [
      ["About", "#about"],
      ["Collections", "#collections"],
      ["Atelier", "#atelier"],
      ["Press & Fairs", "#news"],
      ["Contact", "#contact"],
    ] as [string, string][],
    colLegalLinks: "Legal",
    legal: [
      ["Privacy Policy", "#"],
      ["Cookie Policy", "#"],
      ["Private Area", "#admin"],
      ["Credits", "#"],
    ] as [string, string][],
  },
} as const;
