export const en = {
  nav: {
    home: "Home",
    about: "Company",
    collections: "Catalogue",
    atelier: "Workshop",
    news: "News",
    contact: "Contact",
  },
  cta: {
    contact: "Contact",
    primary: "Our services",
    secondary: "The catalogue",
    all: "Full catalogue",
    learn: "Read",
    info: "Request information",
  },
  header: { since: "since 1989" },
  hero: {
    eyebrow: "",
    titlePre: "Handcrafted jewellery",
    titleEm: "since 1989 RGR has turned emotions into jewellery",
    lede: "Founded in Arezzo in 1989, R.G.R. creates handcrafted Made in Italy jewellery by combining experience, creativity and innovation.",
    metaLeft: "Goldsmith workshop - Made in Italy",
    metaRight: "Via Piero Calamandrei - Arezzo",
  },
  about: {
    eyebrow: "The company",
    titlePre: "THE STORY OF A",
    titleEm: "FAMILY",
    quote:
      "Forty years of experience in artisanal craftsmanship to forge jewellery.",
    paragraphs: [
      "R.G.R. was founded in Arezzo in 1989 as an artisan workshop specialising in the processing of precious metals.",
      "From its earliest years, the company stood out for its original creative paths.",
      "With the same enthusiasm as at the beginning and a significant wealth of experience gained over time, R.G.R. continues to turn emotions into jewellery through a distinctive creative sensibility, carefully interpreting market needs and their evolution.",
    ],
  },
  pillars: [
    {
      num: "01",
      label: "Since 1989",
      desc: "Thirty-six years of goldsmith work.",
    },
    {
      num: "02",
      label: "Handmade",
      desc: "Each piece is born from the hands of our goldsmiths.",
    },
    {
      num: "03",
      label: "Made in Italy",
      desc: "Tradition and materials, entirely Italian.",
    },
    {
      num: "04",
      label: "Arezzo",
      desc: "Rooted in the Arezzo goldsmith district.",
    },
  ],
  manifesto: {
    eyebrow: "RGR manifesto",
    ariaLabel: "Animated RGR manifesto",
    lines: [
      "OROAREZZO",
      "VICENZAORO",
      "FINE JEWELLERY",
      "MADE IN ITALY",
      "ARTISANAL EXCELLENCE",
    ],
  },
  catalogue: {
    eyebrow: "The catalogue",
    titlePre: "Unique lines,",
    titleEm: "wire wound on template.",
    lede: "Unique collections designed to enhance our techniques and stones.",
    tabs: ["All", "Rings", "Bracelets", "Necklaces", "Earrings"],
  },
  atelier: {
    eyebrow: "The workshop",
    titlePre: "Expert hands,",
    titleEm: "advanced technologies.",
    paragraphs: [
      "In our Arezzo workshop, goldsmith tradition coexists with the latest generation of processing tools. Every jewel goes through dozens of precise gestures before leaving the goldsmith's bench.",
      "Attention to detail is not a finish: it is the way we conceive each piece from the beginning.",
    ],
    tags: [
      "Craftsmanship",
      "Precision",
      "Goldsmith tradition",
      "Technology",
      "Arezzo",
      "Wound wire",
    ],
  },
  news: {
    eyebrow: "Adv Press - Fairs",
    titlePre: "Between international fairs",
    titleEm: "and glossy pages.",
    lede: "RGR's presence at industry events and the covers dedicated to our work.",
    filterAll: "All",
    filterFairs: "Fairs",
    filterPress: "Press",
    loadMore: "Load more",
  },
  footer: {
    claim: "Handcrafted jewellery since 1989. RGR turns emotions into jewellery.",
    colVisit: "Visit Us",
    addrTitle: "Via Pietro Calamandrei, 253 A/11",
    addrLines: [
      "52100 Arezzo - Italy",
    ],
    colContact: "Contact",
    contact: [
      ["Email", "info@rgrhandmade.it"],
      ["Phone", "0575-299101"],
    ] as [string, string][],
    form: {
      eyebrow: "Contact",
      title: "Write to us.",
      lede: "For information or appointments at the workshop.",
      contactTitle: "Direct contact",
      formTitle: "Leave your contact details.",
      name: "Full name",
      company: "Company / contact person",
      email: "Email",
      phone: "Phone",
      message: "Message",
      messagePlaceholder: "Your message",
      privacyBefore: "I confirm that I have read",
      privacyLink: "the privacy notice",
      privacyAfter: ".",
      privacyHref: "/privacy-policy",
      submit: "Send",
      sending: "Sending…",
      success: "Thank you! Your message has been sent. We will get back to you soon.",
      error: "Sending failed. Please try again shortly or email us at info@rgrhandmade.it.",
      note: "We will reply from the workshop.",
    },
    colExplore: "Explore",
    explore: [
      ["Company", "#about"],
      ["Catalogue", "#collections"],
      ["Workshop", "#atelier"],
      ["News & Fairs", "#news"],
      ["Contact", "#contact"],
    ] as [string, string][],
    colLegalLinks: "Legal",
    legal: [
      ["Privacy Policy", "/privacy-policy"],
      ["Cookie Policy", "/cookie-policy"],
      ["Terms of Use", "/condizioni-uso"],
      ["Manage cookies", "#cookie-settings"],
      ["Private Area", "#admin"],
      ["Credits", "#"],
    ] as [string, string][],
  },
} as const;
