export const it = {
  nav: {
    home: "Home",
    about: "Azienda",
    collections: "Catalogo",
    atelier: "Laboratorio",
    news: "News",
    contact: "Contatti",
  },
  cta: {
    contact: "Contatti",
    primary: "Nostri servizi",
    secondary: "Il catalogo",
    all: "Tutto il catalogo",
    learn: "Leggi",
    info: "Richiedi informazioni",
  },
  header: { since: "dal 1989" },
  hero: {
    eyebrow: "",
    titlePre: "Gioielli artigianali",
    titleEm: "dal 1989 RGR trasforma emozioni in gioielli",
    lede: "R.G.R, fondata ad Arezzo nel 1989, realizza gioielli artigianali Made in Italy unendo esperienza, creatività ed innovazione.",
    metaLeft: "Laboratorio orafo · Made in Italy",
    metaRight: "Via Piero Calamandrei · Arezzo",
  },
  about: {
    eyebrow: "L'azienda",
    titlePre: "Una storia di mani,",
    titleEm: "metallo e luce.",
    quote:
      "Materializzare in gioielli le emozioni, attraverso uno spiccato senso creativo.",
    paragraphs: [
      "R.G.R. nasce ad Arezzo nel 1989 come laboratorio artigianale specializzato nelle lavorazioni di metalli preziosi.",
      "Già nei primi anni di attività, l’Azienda si contraddistingue per percorsi creativi originali.",
      "Con lo stesso entusiasmo delle origini e un importante bagaglio di esperienza maturato nel tempo, R.G.R. continua a trasformare emozioni in gioielli attraverso uno spiccato senso creativo, interpretando con attenzione le esigenze del mercato e le sue evoluzioni.",
    ],
  },
  pillars: [
    {
      num: "01",
      label: "Dal 1989",
      desc: "Trentasei anni di lavorazione orafa.",
    },
    {
      num: "02",
      label: "Handmade",
      desc: "Ogni pezzo nasce dalle mani dei nostri orafi.",
    },
    {
      num: "03",
      label: "Made in Italy",
      desc: "Tradizione e materia, interamente italiane.",
    },
    {
      num: "04",
      label: "Arezzo",
      desc: "Radici nel distretto orafo aretino.",
    },
  ],
  manifesto: {
    eyebrow: "Manifesto RGR",
    ariaLabel: "Manifesto RGR in movimento",
    lines: [
      "OROAREZZO",
      "VICENZAORO",
      "FINE JEWELLERY",
      "MADE IN ITALY",
      "ARTISANAL EXCELLENCE",
    ],
  },
  catalogue: {
    eyebrow: "Il catalogo",
    titlePre: "Linee uniche,",
    titleEm: "filo avvolto su sagoma.",
    lede: "Collezioni uniche pensate per esaltare le nostre tecniche e le pietre.",
    tabs: ["Tutte", "Anelli", "Bracciali", "Collane", "Orecchini"],
  },
  atelier: {
    eyebrow: "Il laboratorio",
    titlePre: "Mani esperte,",
    titleEm: "tecnologie evolute.",
    paragraphs: [
      "Nel nostro laboratorio aretino la tradizione orafa convive con strumenti di lavorazione di ultima generazione. Ogni gioiello attraversa decine di gesti precisi prima di lasciare il banco dell'orafo.",
      "La cura del dettaglio non è una finitura: è il modo in cui pensiamo il pezzo dall'inizio.",
    ],
    tags: [
      "Artigianalità",
      "Precisione",
      "Tradizione orafa",
      "Tecnologia",
      "Arezzo",
      "Filo avvolto",
    ],
  },
  news: {
    eyebrow: "Adv Press · Fiere",
    titlePre: "Tra fiere internazionali",
    titleEm: "e pagine patinate.",
    lede: "Le presenze di RGR negli appuntamenti di settore e le copertine dedicate al nostro lavoro.",
    filterAll: "Tutto",
    filterFairs: "Fiere",
    filterPress: "Press",
    loadMore: "Carica altri",
  },
  footer: {
    claim: "Gioielli artigianali dal 1989. RGR trasforma emozioni in gioielli.",
    colVisit: "Atelier",
    addrTitle: "Via Pietro Calamandrei, 253 A/11",
    addrLines: [
      "52100 Arezzo · Italy",
    ],
    form: {
      eyebrow: "Contatti",
      title: "Scrivici.",
      lede: "Per informazioni o appuntamenti in laboratorio.",
      detailsTitle: "Laboratorio",
      details: [
        "Collezioni RGR e gioielli su misura.",
        "Arezzo, su appuntamento.",
        "Risposta entro 1-2 giorni lavorativi.",
      ],
      formTitle: "Lascia i tuoi riferimenti.",
      name: "Nome e cognome",
      company: "Azienda / referente",
      email: "Email",
      phone: "Telefono",
      message: "Messaggio",
      messagePlaceholder: "Il tuo messaggio",
      privacy: "Acconsento al trattamento dei dati per essere ricontattato.",
      submit: "Invia",
      note: "Ti risponderemo dal laboratorio.",
    },
    colExplore: "Esplora",
    explore: [
      ["Azienda", "#about"],
      ["Catalogo", "#collections"],
      ["Laboratorio", "#atelier"],
      ["News & Fiere", "#news"],
      ["Contatti", "#contact"],
    ] as [string, string][],
    colLegalLinks: "Legale",
    legal: [
      ["Privacy Policy", "#"],
      ["Cookie Policy", "#"],
      ["Area Riservata", "#admin"],
      ["Credits", "#"],
    ] as [string, string][],
  },
} as const;
